[package]
name = "slants_solver"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"

[lib]
name = "slants"
path = "src/lib.rs"

[[bin]]
name = "solve_puzzles"
path = "src/bin/solve_puzzles.rs"

[[bin]]
name = "gen_puzzles"
path = "src/bin/gen_puzzles.rs"
